In [38]:
import numpy as np
import pandas as pd

In [39]:
df_retas = pd.read_csv('https://github.com/tnpb-1st/if684-projeto-busca-estrela/raw/master/retas.csv', index_col=0, decimal=',').astype(float)
df_real = pd.read_csv('https://github.com/tnpb-1st/if684-projeto-busca-estrela/raw/master/real.csv', index_col=0, decimal=',').astype(float)
df_linhas = pd.read_csv('https://github.com/tnpb-1st/if684-projeto-busca-estrela/raw/master/colors.csv', index_col=0)

In [40]:
df_retas

,E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14
E1,0.0,40.0,74.0,99.2,145.6,155.2,143.2,101.6,70.4,36.4,66.8,109.2,110.4,119.2
E2,40.0,0.0,34.0,59.2,106.4,116.4,104.4,69.2,40.0,14.0,62.0,83.6,76.4,87.2
E3,74.0,34.0,0.0,25.2,72.8,82.4,70.4,54.4,37.6,41.2,78.0,76.4,48.4,66.4
E4,99.2,59.2,25.2,0.0,48.0,57.6,46.0,49.6,50.4,66.8,94.4,74.4,42.4,61.6
E5,145.6,106.4,72.8,48.0,0.0,12.0,9.6,77.6,93.2,112.8,136.8,99.2,58.0,71.6
E6,155.2,116.4,82.4,57.6,12.0,0.0,13.2,89.2,102.8,121.2,146.8,110.4,60.8,72.8
E7,143.2,104.4,70.4,46.0,9.6,13.2,0.0,80.0,92.0,109.2,136.8,102.8,49.6,62.4
E8,101.6,69.2,54.4,49.6,77.6,89.2,80.0,0.0,32.8,81.2,64.4,25.6,90.8,110.4
E9,70.4,40.0,37.6,50.4,93.2,102.8,92.0,32.8,0.0,54.0,44.8,43.6,84.8,106.4
E10,36.4,14.0,41.2,66.8,112.8,121.2,109.2,81.2,54.0,0.0,70.4,96.8,74.8,84.8
E11,66.8,62.0,78.0,94.4,136.8,146.8,136.8,64.4,44.8,70.4,0.0,56.8,126.0,142.0
E12,109.2,83.6,76.4,74.4,99.2,110.4,102.8,25.6,43.6,96.8,56.8,0.0,115.2,134.4
E13,110.4,76.4,48.4,42.4,58.0,60.8,49.6,90.8,84.8,74.8,126.0,115.2,0.0,20.4
E14,119.2,87.2,66.4,61.6,71.6,72.8,62.4,110.4,106.4,84.8,142.0,134.4,20.4,0.0

In [41]:
df_real

,E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14
E1,NaN,20.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E2,20.0,NaN,17.0,NaN,NaN,NaN,NaN,NaN,20.0,7.0,NaN,NaN,NaN,NaN
E3,NaN,17.0,NaN,12.6,NaN,NaN,NaN,NaN,18.8,NaN,NaN,NaN,37.4,NaN
E4,NaN,NaN,12.6,NaN,26.0,NaN,NaN,30.6,NaN,NaN,NaN,NaN,25.6,NaN
E5,NaN,NaN,NaN,26.0,NaN,6.0,4.8,60.0,NaN,NaN,NaN,NaN,NaN,NaN
E6,NaN,NaN,NaN,NaN,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E7,NaN,NaN,NaN,NaN,4.8,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E8,NaN,NaN,NaN,30.6,60.0,NaN,NaN,NaN,19.2,NaN,NaN,12.8,NaN,NaN
E9,NaN,20.0,18.8,NaN,NaN,NaN,NaN,19.2,NaN,NaN,24.4,NaN,NaN,NaN
E10,NaN,7.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,24.4,NaN,NaN,NaN,NaN,NaN
E12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,12.8,NaN,NaN,NaN,NaN,NaN,NaN
E13,NaN,NaN,37.4,25.6,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2
E14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10.2,NaN

In [42]:
df_linhas

,E1,E2,E3,E4,E5,E6,E7,E8,E9,E10,E11,E12,E13,E14
E1,NaN,blue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E2,blue,NaN,blue,NaN,NaN,NaN,NaN,NaN,yellow,yellow,NaN,NaN,NaN,NaN
E3,NaN,blue,NaN,blue,NaN,NaN,NaN,NaN,red,NaN,NaN,NaN,red,NaN
E4,NaN,NaN,blue,NaN,blue,NaN,NaN,green,NaN,NaN,NaN,NaN,green,NaN
E5,NaN,NaN,NaN,blue,NaN,blue,yellow,yellow,NaN,NaN,NaN,NaN,NaN,NaN
E6,NaN,NaN,NaN,NaN,blue,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E7,NaN,NaN,NaN,NaN,yellow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E8,NaN,NaN,NaN,green,yellow,NaN,NaN,NaN,yellow,NaN,NaN,green,NaN,NaN
E9,NaN,yellow,red,NaN,NaN,NaN,NaN,yellow,NaN,NaN,red,NaN,NaN,NaN
E10,NaN,yellow,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
E11,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,red,NaN,NaN,NaN,NaN,NaN
E12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,green,NaN,NaN,NaN,NaN,NaN,NaN
E13,NaN,NaN,red,green,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,green
E14,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,green,NaN

In [43]:
class BinaryHeap:
  def _swap(self, i, j):
    self._container[i], self._container[j] = self._container[j], self._container[i]

  def _parent(self, i):
    return (i - 1) // 2
  
  def _left(self, i):
    return 2 * i + 1

  def _right(self, i):
    return 2 * i + 2

  def _has_left(self, i):
    return self._left(i) < self._size
  
  def _has_right(self, i):
    return self._right(i) < self._size
  
  def _upheap(self, i):
    parent = self._parent(i)
    if i > 0 and self._container[i][0] < self._container[parent][0]:
      self._swap(i, parent)
      self._upheap(parent)
  
  def _downheap(self, i):
    if self._has_left(i):
      left = self._left(i)
      small_child = left
      if self._has_right(i):
        right = self._right(i)
        if self._container[right][0] < self._container[left][0]:
          small_child = right
      if self._container[small_child][0] < self._container[i][0]:
        self._swap(i, small_child)
        self._downheap(small_child)
  
  def __init__(self):
    self._container = []
    self._size = 0
  
  def push(self, est:tuple):
    self._container.append(est)
    self._size += 1
    self._upheap(self._size - 1)

  def extract_min(self):
    if self._size == 0:
      raise IndexError('Empty Heap!')
    self._swap(0, self._size - 1)
    return_value = self._container.pop()
    self._size -= 1
    self._downheap(0)
    return return_value
  
  def build_heap(self, alist:list):
    i = len(alist) // 2
    self._size = len(alist)
    self._container = alist[:]
    while (i >= 0):
        self._downheap(i)
        i = i - 1
  
  def empty(self)->bool:
    return self._size == 0
  
  def __len__(self):
    return self._size
  
  def __str__(self):
    return str(self._container)

  def __repr__(self):
    return str(self._container)

In [44]:
class Mapa:
  def __init__(self, df_real, df_retas, df_linhas):
    self.est_dists = df_real
    self.h_dists = df_retas
    self.linhas = df_linhas
  
  def calc_dist_real(self, e1, e2, linha_atual):
    _f = self.est_dists.loc[e1,e2]
    if self.linhas.loc[e1,e2] != linha_atual:
      _f += 4
    return _f
  
  def calcula_dist_heuristica(self, e1, e2):
    return self.h_dists.loc[e1,e2]

In [45]:
mapa = Mapa(df_real, df_retas, df_linhas)

In [46]:
def calcula_caminho(e0, l0, ef):
  fronteira = BinaryHeap()
  predecessors = {k : {} for k in df_real.index}
  infos = {k : {} for k in df_real.index}
  caminho = []
  visited = []
  l_atual = l0
  # custo_total, (custo_real, predecessor, estacao, l_atual)
  fronteira.push((0,(0, -1, e0, l0)))
  while not(fronteira.empty()):
    c_total, est_info = fronteira.extract_min()
    c_real, pred, est_atual, l_atual = est_info
    
    if est_atual not in visited:
      visited.append(est_atual)
      predecessors[est_atual] = pred
    else:
      continue
    
    infos[est_atual] = est_info
    if est_atual == ef:
      break
    for viz, d in df_real.loc[est_atual,df_real[est_atual].notnull()].items():
      _f = mapa.calc_dist_real(est_atual, viz, l_atual)
      _g = _f + mapa.calcula_dist_heuristica(viz, ef)
      print(f"{est_atual} -> {viz}, g: {_g}, f: {_f}")
      fronteira.push((_g, (_f, est_atual, viz, df_linhas.loc[est_atual, viz])))
  
  _e = ef
  custo = 0
  while _e != -1:
    c_real, pred, est_atual, l_atual = infos[_e]
    custo += c_real
    caminho.append(est_atual)
    _e = pred
  caminho.reverse()
  print('\\' + '=' * 80 + '|')
  print(f"o itinerario da viagem é: {' -> '.join(caminho)}")
  print(f"o tempo total estimado da viagem é: {custo:.2f} minutos")

In [47]:
calcula_caminho('E3', 'red' ,'E14')

E3 -> E2, g: 108.2, f: 21.0
E3 -> E4, g: 78.2, f: 16.6
E3 -> E9, g: 125.2, f: 18.8
E3 -> E13, g: 57.8, f: 37.4
E13 -> E3, g: 103.80000000000001, f: 37.4
E13 -> E4, g: 91.2, f: 29.6
E13 -> E14, g: 14.2, f: 14.2
\================================================================================|
o itinerario da viagem é: E3 -> E13 -> E14
o tempo total estimado da viagem é: 51.60 minutos